import { UserRole, RoleConfig, UserProfile } from '../types/auth';

export const ROLE_CONFIGS: Record<UserRole, RoleConfig> = {
  patient: {
    role: 'patient',
    title: 'Patient Portal',
    subtitle: 'Sign in to access your consultations, health records & medical appointments',
    iconName: 'person-outline',
    identifierLabel: 'Email or Mobile Number',
    identifierPlaceholder: 'name@domain.com or 10-digit number',
    identifierRightActionText: 'UHID / Patient ID',
    defaultEmailOrId: 'patient@example.com',
    demoPassword: '••••••••••••',
    portalName: 'Patient Health Dashboard',
    primaryColor: '#0080FF',
    badgeText: 'Verified Patient',
  },
  doctor: {
    role: 'doctor',
    title: 'Doctor OPD Portal',
    subtitle: 'Sign in to manage your OPD queues, clinic schedules & consultations',
    iconName: 'medkit-outline',
    identifierLabel: 'Doctor Email or Mobile Number',
    identifierPlaceholder: 'doctor@domain.com or NMC / Reg No',
    identifierRightActionText: 'NMC / Reg No',
    defaultEmailOrId: 'doctor@example.com',
    demoPassword: '••••••••••••',
    portalName: 'Doctor OPD & Clinics',
    primaryColor: '#0284C7',
    badgeText: 'NMC Verified Doctor',
  },
  clinic: {
    role: 'clinic',
    title: 'Clinic & Reception Portal',
    subtitle: 'Sign in to manage OPD queues, patient tokens & live clinic operations',
    iconName: 'business-outline',
    identifierLabel: 'Clinic Code or Reception Email',
    identifierPlaceholder: 'clinic@domain.com or Clinic License ID',
    identifierRightActionText: 'Clinic Reg ID',
    defaultEmailOrId: 'clinic@example.com',
    demoPassword: '••••••••••••',
    portalName: 'Clinic Operations & Queue Hub',
    primaryColor: '#2563EB',
    badgeText: 'City Medical Reception',
  },
  lab: {
    role: 'lab',
    title: 'Diagnostic & Lab Portal',
    subtitle: 'Sign in to manage diagnostic orders, sample collections & test reports',
    iconName: 'flask-outline',
    identifierLabel: 'Lab Code or Admin Email',
    identifierPlaceholder: 'lab@domain.com or Lab License ID',
    identifierRightActionText: 'Diagnostic Reg ID',
    defaultEmailOrId: 'lab@example.com',
    demoPassword: '••••••••••••',
    portalName: 'Diagnostic Sample & Report Hub',
    primaryColor: '#0D9488',
    badgeText: 'NABL Accredited Lab',
  },
};

export const DEMO_USERS: Record<UserRole, UserProfile> = {
  patient: {
    id: '00000000-0000-4000-8000-000000000001',
    name: 'Alex Morgan',
    role: 'patient',
    identifier: 'UPC-PAT-000001',
    email: 'patient@example.com',
    phone: '+91 98000 00001',
    avatarUrl:
      'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    specialtyOrTagline: 'UHID: UPC-PAT-000001 • Blood Group O+',
    bloodGroup: 'O+ Positive',
    dateOfBirth: '01 / 01 / 1990',
    gender: 'male',
    address: '123 Healthcare Way, Sector 1, Metro City',
    isVerified: true,
  },
  doctor: {
    id: '00000000-0000-4000-8000-000000000002',
    name: 'Dr. Sam Wilson',
    role: 'doctor',
    identifier: 'DOC-REG-000002',
    email: 'doctor@example.com',
    phone: '+91 98000 00002',
    avatarUrl:
      'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80',
    specialtyOrTagline: 'General Physician • 10+ Yrs Exp',
    isVerified: true,
  },
  clinic: {
    id: '00000000-0000-4000-8000-000000000003',
    name: 'City Care Clinic',
    role: 'clinic',
    identifier: 'CLI-REG-000003',
    email: 'clinic@example.com',
    phone: '+91 98000 00003',
    avatarUrl:
      'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=200&q=80',
    specialtyOrTagline: 'City Care Clinic • Metro City',
    address: '456 Clinic Avenue, Metro City - 110001',
    isVerified: true,
  },
  lab: {
    id: '00000000-0000-4000-8000-000000000004',
    name: 'Metro Diagnostic Centre',
    role: 'lab',
    identifier: 'LAB-REG-000004',
    email: 'lab@example.com',
    phone: '+91 98000 00004',
    avatarUrl:
      'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=200&q=80',
    specialtyOrTagline: 'NABL Accredited • Diagnostic & Pathology Center',
    isVerified: true,
  },
};
